### ISSUE TITLE
ERR Dial failed: dial tcp: lookup localhost: device or resource busy

### ISSUE THREAD

**Issue by adwpc** [pion/ion-load-tool#8]
```
./ion-load-tool -ion-url 'wss://localhost:8443/ws?peer=b2dae52e-3ead-47b9-abbe-928b379bfa4f' -consume  -clients 1000 -seconds 6000 -stagger 0.2
```
Found this error when change -stagger to 0.2 or 0.5

Maybe this error is from biz

**Comment by jbrady42** [comment]
Also just changing that to 127.0.0.1 would avoid the dns hit so there would be no "lookup localhost"

**Comment by jbrady42** [comment]
@adwpc can you try this using the `-ion-url wss://127.0.0.1:8443 -stagger 0` and see if you have the same problem. I have not been able to replicate the issue locally.
